### ISSUE TITLE
Still Maintaining This Repo and API?

### ISSUE THREAD

**Issue by MikeiLL** [knpuniversity/oauth#62]
Hi and thanks for the tutorial.

I'm getting an error that Client Credentials are Invalid, though the content of $request['client_id'] and $request['client_secret'] matches those in the Web GUI.

Guzzle Version 3.8.

```
PHP Fatal error:  Uncaught Guzzle\Http\Exception\ClientErrorResponseException: Client error response
[status code] 400
[reason phrase] Bad Request
[url] http://coop.apps.knpuniversity.com/token in /Users/path/oauth/cron/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43
```

Am I missing a step? Is the API still operational? Thanks and apologies for the spam.

**Comment by bocharsky-bw** [comment]
Hey @MikeiLL,

You say you get an error about invalid credentials, but I do not see this error in your logs, only "Bad Request" one. Is there also another error?

Probably your request contains invalid data (not invalid client credentials), or you missed some required data, or you send this request to the wrong entry point?

Also, could you point us to exact tutorial page where you get this error? It's difficult to understand based on your description.

Cheers!

**Comment by MikeiLL** [comment]
Oh yay. Thanks, man. The tutorial is at https://knpuniversity.com/screencast/oauth/client-credentials and my guess is that maybe the version of Guzzle in the composer file and the one the tutorial is using have diverged and that I'm making the call wrong–or should use a different Guzzle version.

This is the stack trace:
```
Stack trace:
#0 /path/oauth/cron/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /path/oauth/cron/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /Users/mikekilmer/Shed/oauth/cron/vendor/symfony/ in /path/oauth/cron/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php on line 43
```

If you do have input to offer I'll welcome it.

**Comment by MikeiLL** [comment]
Using GuzzleHttp/Guzzle 6 now with this code:

```
include __DIR__.'/vendor/autoload.php';
use GuzzleHttp\Client;

// create our http client (Guzzle)
$client = new Client(['base_uri' => 'http://coop.apps.knpuniversity.com', 'defaults' => [
				'exceptions' => false ]]);
				
$res = $client->request('GET', 'http://coop.apps.knpuniversity.com', array(
    'request.options' => array(
        'exceptions' => true,
    )
));
echo $res->getStatusCode();
echo "\n\n";

$http = new Client(['base_uri' => 'http://coop.apps.knpuniversity.com', 'defaults' => [
				'exceptions' => false ]]);

$response = $http->request('POST', '/token', [
	'form_params' => [
		'client_id'     => 'APP_ID',
		'client_secret' => 'app_secret',
		'grant_type'    => 'client_credentials'
	]
]); 

var_dump($response);die;
```

This response:
```
$ php collect_eggs.php 
200

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST http://coop.apps.knpuniversity.com/token` resulted in a `400 Bad Request` response:
{"error":"invalid_client","error_description":"The client credentials are invalid"}
 in /Users/mikekilmer/Shed/oauth/cron/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /Path/cron/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /Path/cron/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /Path/cron/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /Path/cron/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closur in /Users/mikekilmer/Shed/oauth/cron/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST http://coop.apps.knpuniversity.com/token` resulted in a `400 Bad Request` response:
{"error":"invalid_client","error_description":"The client credentials are invalid"}
 in /Path/cron/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

GuzzleHttp\Exception\ClientException: Client error: `POST http://coop.apps.knpuniversity.com/token` resulted in a `400 Bad Request` response:
{"error":"invalid_client","error_description":"The client credentials are invalid"}
 in /Path/cron/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

Call Stack:
    0.0008     365216   1. {main}() /Path/cron/collect_eggs.php:0
    1.9803    1562872   2. GuzzleHttp\Client->request() /Path/cron/collect_eggs.php:24
    2.0816    1579776   3. GuzzleHttp\Promise\Promise->wait() /Path/cron/vendor/guzzlehttp/guzzle/src/Client.php:131
```

Not sure where else to poke around at the moment. It seems like the Http request is succeeding in getting a response from the API:

```
{"error":"invalid_client","error_description":"The client credentials are invalid"}
```

Right?

**Comment by MikeiLL** [comment]
Wait. Working now! Created a third APP, this one has all six interactions in it's Scope:

```
    barn-unlock
    toiletseat-down
    chickens-feed
    eggs-collect
    eggs-count
    profile
```

Maybe that was a step in the Tutorial I had missed.

**Comment by bocharsky-bw** [comment]
Hey Mike, glad you got it working by yourself even quicker than I reply you!

Cheers!
